### ISSUE TITLE
connection refused when running on buidlerevm

### ISSUE THREAD

**Issue by jo-es** [cgewecke/buidler-gas-reporter#15]
I'm getting `connect ECONNREFUSED 127.0.0.1:8545` when running tests with the builder-gas-reporter plugin enabled. I'm also getting the same output when using eth-gas-reporter directly via mocha configs in buidler.config.js.

```sh
❯ ap-contracts yarn test
yarn run v1.16.0
$ buidler test
All contracts have already been compiled, skipping compilation.
An unexpected error occurred:

Error: connect ECONNREFUSED 127.0.0.1:8545
    at extractValue (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/ap-contracts/node_modules/sync-rpc/lib/index.js:165:19)
    at /Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/ap-contracts/node_modules/sync-rpc/lib/index.js:175:12
    at request (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/ap-contracts/node_modules/sync-request/lib/index.js:28:15)
    at Sync.request (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/ap-contracts/node_modules/eth-gas-reporter/lib/syncRequest.js:65:17)
    at Sync.getNetworkId (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/ap-contracts/node_modules/eth-gas-reporter/lib/syncRequest.js:17:17)
    at new Artifactor (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/ap-contracts/node_modules/eth-gas-reporter/lib/artifactor.js:20:32)
    at GasData.initialize (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/ap-contracts/node_modules/eth-gas-reporter/lib/gasData.js:31:24)
    at Runner.Gas.runner.on (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/ap-contracts/node_modules/eth-gas-reporter/index.js:45:16)
    at Runner.emit (events.js:203:15)
    at start (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/ap-contracts/node_modules/mocha/lib/runner.js:848:10)
    at Runner.run (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/ap-contracts/node_modules/mocha/lib/runner.js:876:5)
    at Mocha.run (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/ap-contracts/node_modules/mocha/lib/mocha.js:612:17)
    at Promise (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/ap-contracts/node_modules/@nomiclabs/buidler/src/builtin-tasks/test.ts:55:15)
    at new Promise (<anonymous>)
    at SimpleTaskDefinition.config_env_1.internalTask.addOptionalVariadicPositionalParam.setAction [as action] (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/ap-contracts/node_modules/@nomiclabs/buidler/src/builtin-tasks/test.ts:54:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Repository for reference: [ap-contracts](https://github.com/atpar/ap-monorepo/blob/master/packages/ap-contracts/buidler.config.js)

- buidler: ^1.3.0
- buidler-gas-reporter:  ^0.1.3
- eth-gas-reporter: ^0.2.17

**Comment by cgewecke** [comment]
@jo-es 

Have added some tests for buidlerevm in #17. It looks like it's necessary to launch buidlerevm [as an independent node][1] to get eth-gas-reporter to connect to it correctly. Sort of like ganache. 

The gas reporter makes synchronous calls to the client to fetch data as each test executes (necessary because mocha's reporter hooks are sync). This requires that the client run in a separate process. 

If you have a chance, could you see if doing that resolves on your end? I believe the independent node will be on network `localhost` and you can define network settings for it under that key.

[1]: https://buidler.dev/buidler-evm/#connecting-to-buidler-evm-from-wallets-and-other-software

**Comment by jo-es** [comment]
Can confirm this workaround fixes the issue.

**Comment by cgewecke** [comment]
Hi @jo-es.

`0.1.4` now supports BuidlerEVM without any independent node requirement or special config. It's quite a bit faster too.

Closing, please just lmk if you run into any issues upgrading.

**Comment by jo-es** [comment]
@cgewecke Thanks 🙌. Can confirm that it works seamlessly again.
